# Generated by Django 4.2.1 on 2023-05-30 08:57

from django.db import migrations, models
import mappings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlMapping',
            fields=[
                ('long_url', models.URLField(db_index=True, editable=False, max_length=255, unique=True)),
                ('hash', models.CharField(db_index=True, default=mappings.models.generate_random_hash, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
